#!/usr/bin/lua

local appname = "Icemenu 19.09.30-1"
local iconDirs = {
	"/usr/share/icons/gnome/32x32","/usr/share/icons/hicolor/32x32","/usr/share/icons/hicolor/48x48/",
	"/usr/share/icons/hicolor","/usr/share/icons/Puppy Flat/32/","/usr/share/icons/Puppy Standard/",
	"/usr/share/pixmaps","/usr/share/games","/usr/share/app-install/icons","/usr/share/icons/Mint-X/apps/32/",
	"/usr/share/icons/hicolor/scalable","/usr/share/icewm/icons","usr/share/icewm/icons/menuitems"
}
local rootBase="" -- Base dir for icon search
local iconTable = {}
local terminal = "x-terminal-emulator -e "
local par
local appsdir = "/usr/share/applications"

local locales = {
	de = {exit = "Beenden", logout = "Abmelden", reboot = "Neustart", poweroff = "Ausschalten",
			terminal = "Terminal", appfinder = "AppFinder", development = "Entwicklung",
			graphics = "Grafik", games = "Spiele", multimedia = "Multimedia", office = "Büro",
			science = "Wissenschaft", education = "Erziehung", network = "Netzwerk", settings = "Einstellungen",
			desktop = "Desktop", hardware = "Hardware", all = "Alle", system = "System",
			filesystem = "Dateisystem", safety = "Sicherheit/Monitoring", terminals = "Terminals",
			tools = "Werkzeuge", mywebsite = "Uwes Info-Seite"
			},
	en = {exit = "Exit", logout = "Logout", reboot = "Reboot", poweroff = "Power off",
			terminal = "Terminal", appfinder = "AppFinder", development = "Development",
			graphics = "Graphics", games = "Games", multimedia = "Multimedia", office = "Office",
			science = "Science", education = "Education", network = "Network", settings = "Settings",
			desktop = "Desktop", hardware = "Hardware", all = "All", system = "System",
			filesystem = "Filesystem", safety = "Safety/Monitoring", terminals = "Terminals",
			tools = "Tools", mywebsite = "Uwes Info-Page" 
			}
}

local lang = "en"
local outdir = ""
local outfile
local homedir

-- output ---------------------------------------------------------------------

function out(outstr)
	io.write(outstr.."\n")
end

-- parse command line ---------------------------------------------------------

function parseCmdLine()
	-- print help if selected
	if arg[1] == "-h" or arg[1] == "h" or arg[1] == "--help" then
		print("\n"..appname.." - Creates an icewm menu file!\n")
		print([[usage: icemenu [options] [appsDir]
Available options are:
-c            short comment line after program name in  menu
-h            show help page
-l language   make menu in language given (de,en)
-o directory  put output to file directory/menu
-r directory  root directory for icon and application search
-w            write menu file to $HOME/.icewm/menu

[appsDir] ist the directory where to search application desktop files, defaults to /usr/share/applications.
If option '-r' is given, applications and icons are searched in a directory tree starting at the given directory.
Examples:
icemenu             search applications in '/usr/share/applications', icons in '/usr/share/icons'.
icemenu -r rootfs   search applications in 'rootfs/usr/share/applications', icons in 'rootfs/usr/share/icons'.
icemenu -c          search applications/icons in default dirs, add short comment to program title.

Output is done to stdout. To create a menu file, redirect output! (e.g. "icemenu >~/.icewm/menu")
]])
		os.exit()
	end

	local i = 1
	while i <= #arg do
		if arg[i] == "-c" or arg[i] == "c" then
			par = arg[i]
		elseif arg[i] == "-r" or arg[i] == "r" then
			rootBase = arg[i+1]
			i = i + 1
		elseif arg[i] == "-o" or arg[i] == "o" then
			outdir = arg[i+1]
			i = i + 1
			outfile = io.open(outdir.."/menu","w")
			io.output(outfile)
		elseif arg[i] == "-w" or arg[i] == "w" then
			outdir = shellTable("echo $HOME")[1].."/.icewm"
			outfile = io.open(outdir.."/menu","w")
			io.output(outfile)
		elseif arg[i] == "-l" or arg[i] == "l" then
			lang = arg[i+1]
			i = i + 1
			if lang ~= "de" and lang ~= "en" then
				lang = "en"
			end
		else appsdir = arg[i]
		end
		i = i + 1
	end
end -- of parseCmdLine

-- return table with lines of shell command output ----------------------------

function shellTable(command)
	local lines = {}
   local file = io.popen(command,"r")
	for line in file:lines() do
	   table.insert(lines,line)
	end
   file:close()
	return lines
end -- of shell(command)

-- merge 2 tables -------------------------------------------------------------

function table.merge(t1, t2)
   for k,v in ipairs(t2) do
      table.insert(t1, v)
   end
   return t1
end

-- test if file exists --------------------------------------------------------

function fileExists(name)
   local f = io.open(name,"r")
   if f ~= nil then io.close(f) return true else return false end
end

-- read all icons into table --------------------------------------------------

function readIcons()
	for i,v in ipairs(iconDirs) do
		table.merge(iconTable,
			--[[ must cd to 'rootBase' first to get all icons, 'cause 'find' wouldn't get
			all icons sometimes. Dunno the exact reason...]]
			shellTable("AKTDIR=$(pwd); cd "..rootBase.."; find \""..v.."/\" -name \"*.png\" -o -name \"*.xpm\" -o -name \"*.svg\" ; cd $AKTDIR"))
	end -- of for i,v ...
end

-- find an icon ---------------------------------------------------------------

function findIcon(iconName)
	if iconName ~= nil then 
		-- first: test if icon given with full url and has an icon extension can be found
		if fileExists(iconName) and (string.match(iconName,".png")
		or string.match(iconName,".svg")
		or string.match(iconName,".xpm")) then
			return iconName
		else 	-- if not found then search in iconTable for icon
			for i,v in ipairs(iconTable) do
				-- activate/deactivate the corresponing lines if you also want SVG icons to be found!!!
				--if string.find(v,iconName,1,true) and (string.match(v,".png") or string.match(v,".xpm"))then
				if string.find(v,iconName,1,true) and (string.match(v,".png") or string.match(v,".xpm") or string.match(v,".svg")) then
				return v:match("[^("..rootBase:gsub("-","%%-")..")].*") end
			end
		end
	end
	-- return this if nothing is found!
	return "/usr/share/icons/gnome/32x32/actions/gnome-run.png"
end

-- search appTable for line containing expression -----------------------------

function lineSearch( searchTable, searchString)
	local val
	for i,v in ipairs(searchTable) do
		val = string.match(v, searchString)
		if val ~= nil then return val end
	end
	return "nix"
end

--[[ check string for different strings separated by | --------------------------
	if not all are present, return "false", this gives logical "and"! ]]

function checkString(stringVal, compVal)
	for v in string.gmatch(compVal,"%S+") do
		if string.match(stringVal,v) ~= nil then
			return true
		end
	end
	return false
end

-- search items for menu ------------------------------------------------------

function menuItems(appTable, categories)

	-- iterate over apps table

	for i,appEntry in ipairs(appTable) do

		local categoryEntry = lineSearch(appEntry,"Categories=.*$")
	--	out("***"..categoryEntry.."***"..categories.."***"..lineSearch(appEntry,"Exec=.*$") )
		if checkString(categoryEntry, categories) then

			local name = lineSearch(appEntry,"Name."..lang..".=.*$")
			if name == "nix" then
				name = lineSearch(appEntry, "^Name=.*$" )
			end
			name = string.match(name,"=(.*)")
			local comment
			-- read comment if parameter -c or c is given only!
			if par == "c" or par == "-c" then
				comment = lineSearch(appEntry,"Comment."..lang..".=.*$")
				if comment == "nix" then
					comment = lineSearch(appEntry, "Comment=.*$" )
				end
				if comment == "nix" then comment = ""
				else	comment = " - "..string.match(comment,"=(.*)")
				end
			else comment = ""
			end
			local exec = lineSearch(appEntry, "Exec=.*$") 
			exec = string.match(exec, "Exec=(.*)")
			exec = exec:gsub("%%.","")
			local icon = lineSearch(appEntry, "Icon=.*$")
			local terminalTrue = lineSearch(appEntry, "Terminal=.*$")
			local iconFound = findIcon(string.match(icon, "Icon=(.*)"))
			if terminalTrue == "Terminal=true" then
				out("   prog \""..name..comment.."\" \""..iconFound.."\" "..terminal.." "..exec)
			else
				--out(rootBase, name, iconFound, iconFound:match("[^("..rootBase:gsub("-","%%-")..")].*"), exec)
				out("   prog \""..name..comment.."\" \""..iconFound.."\" "..exec)
			end

		end -- of if checkString ...
	end -- of for i,app ...

end

function menuStart(menuTitle, menuIcon)
	out("menu \""..menuTitle.."\" "..findIcon(menuIcon).." {")
end
-- main part ------------------------------------------------------------------

local apps = {}

parseCmdLine()

for i,v in ipairs(shellTable("ls "..rootBase..appsdir.."/*.desktop")) do
	table.insert(apps, shellTable("cat "..v))
end

readIcons()

-- Menu Beenden
out("menu \""..locales[lang].exit.."\" "..findIcon("exit.png").."  {")
out("	prog \""..locales[lang].logout.."\" "..findIcon("gnome-logout.png").." yesno --image=\""..findIcon("gnome-logout").."\" --text-align=center --width=400 --undecorated --height=200 --center --no-markup --text=\"\n\n\nWirklich Benutzer abmelden?\" \"killall uweicewm-session\"")
if fileExists("/sbin/reboot") then 
	out("	prog \""..locales[lang].reboot.."\" "..findIcon("reload.png").." yesno --image=\""..findIcon("reload.png").."\" --text-align=center --width=400 --undecorated --height=200 --center --no-markup --text=\"\n\n\nWirklich Rechner neu starten?\" \"/sbin/reboot\"")
end
if fileExists("/sbin/poweroff") then 
	out("	prog \""..locales[lang].poweroff.."\" "..findIcon("gnome-shutdown.png").." yesno --image=\""..findIcon("gnome-shutdown.png").."\" --text-align=center --undecorated --width=400 --height=200 --center --no-markup --text=\"\n\n\nWirklich ausschalten?\" \"/sbin/poweroff\"")
else
	out("	prog \""..locales[lang].poweroff.."\" "..findIcon("gnome-shutdown.png").." yesno --image=\""..findIcon("gnome-shutdown.png").."\" --text-align=center --undecorated --width=400 --height=200 --center --no-markup --text=\"\n\n\nWirklich ausschalten?\" \"/sbin/shutdown now\"")
end
out("}")
out("separator")
out("prog \""..locales[lang].terminal.."\" "..findIcon("konsole.png").." lxterminal");--io.stderr:write("Gefunden: "..findIcon("reload"))
out("prog \""..locales[lang].appfinder.."\" "..findIcon("edit-find").." xfce4-appfinder")
out("prog \""..locales[lang].mywebsite.."\" "..findIcon("help").." /root/mywebsite/show.sh")
out("prog \""..locales[lang].mywebsite.."\" "..findIcon("help").." /home/uwe/MyDevelop/MyWeb/mywebsite/show.sh")
out("prog \"Menü aktualisieren\" "..findIcon("view-refresh").." icemenu -l de -w ")
out("separator")

-- Entwicklung
menuStart(locales[lang].development, "package_development")
	menuItems(apps, "Development X%-Utility%-development TextEditor")
out("}")

-- Grafik
menuStart(locales[lang].graphics, "package_graphics")
	menuItems(apps, "Graphics X%-Graphic%-viewer Viewer X%-GraphicUtility")
out("}")

-- Spiele
menuStart(locales[lang].games, "package_games")
	menuItems(apps, "Game X%-Fun")
out("}")

-- Multimedia/Audio/Video
menuStart(locales[lang].multimedia, "package_multimedia")
	menuItems(apps, "AudioVideo Video Audio Music")
out("}")

-- Office
menuStart(locales[lang].office, "package_office")
	menuItems(apps, "Office")
out("}")

-- Wissenschaft
menuStart(locales[lang].science, "applications-science")
	menuItems(apps, "Science")
out("}")

-- Erziehung
menuStart(locales[lang].education, "applications-education")
	menuItems(apps, "Education Edutainment")
out("}")

-- Netzwerk
menuStart(locales[lang].network, "nm-device-wireless")
	menuItems(apps, "Network WebBrowser X%-Internet")
out("}")

-- Einstellungen
menuStart(locales[lang].settings, "preferences-other")
	menuStart(locales[lang].desktop, "preferences-desktop-personal")
		menuItems(apps, "DesktopSettings")
	out("}")
	menuStart(locales[lang].hardware, "preferences-desktop-peripherals")
		menuItems(apps, "HardwareSettings")
	out("}")
	menuStart(locales[lang].all, "preferences-other")
		menuItems(apps, "Settings X%-Setup%-puppy")
	out("}")
out("}")

-- System
menuStart(locales[lang].system, "preferences-system-network")
	out("prog \"Midnight-Commander\" "..findIcon("MidnightCommander").." x-terminal-emulator -e mc")
	out("prog \"Pcmanfm\" "..findIcon("system-file-manager").." pcmanfm")
	out("prog \"Thunar\" "..findIcon("thunar").." thunar")
	out("separator")
	out("prog \"Sofware-Manager\" "..findIcon("mintinstall").." mintinstall")
	out("prog \"Update-Manager\" "..findIcon("mintupdate").." mintupdate")
	out("prog \"Synaptic\" "..findIcon("synaptic").." synaptic-pkexec")
	out("separator")
	menuStart(locales[lang].filesystem, "drive-multidisk")
		menuItems(apps, "Filesystem FileTools FileManager")
	out("}")

	menuStart(locales[lang].safety, "security-high")
		menuItems(apps, "Monitor Security")
	out("}")

	menuStart(locales[lang].terminals, "konsole")
		menuItems(apps, "TerminalEmulator X%-Utility%-shell")
	out("}")
	menuStart(locales[lang].all, "preferences-system-network")
		menuItems(apps, "System")
	out("}")
out("}")

-- Werkzeuge
menuStart(locales[lang].tools, "gnome-util")
	menuItems(apps, "Accessiblility Archiving Calculator Clock TextEditor TextTools")
	menuStart(locales[lang].all, "gnome-util")
		menuItems(apps, "Utility")
	out("}")
out("}")

if outdir ~= "" then
	io.close(outfile)
end

-- Testoutput!
--for i,v in ipairs(iconTable) do; out(v); end
